- name: Gather system details and store in a file
  hosts: web
  gather_facts: yes
  tasks:

    - name: Get CPU usage
      shell: |
        CPU_IDLE=$(top -bn1 | grep "Cpu(s)" | awk '{print $8}')
        echo "100 - $CPU_IDLE" | bc
      register: cpu_usage_output

    - name: Get memory usage percentage
      shell: "free | awk '/Mem:/ {printf \"%.2f\", ($3/$2)*100}'"
      register: memory_usage_output

    - name: Get filesystem details
      shell: df -kh
      register: filesystem_details_output

    - name: Store system report in a file on Ansible server
      delegate_to: localhost
      run_once: true
      template:
        src: info.j2
        dest: /tmp/system_details



####################################################

- name: Transfer system report to Windows system
  hosts: windows
  gather_facts: no
  tasks:


    - name: Ensure destination folder exists
      win_file:
        path: C:\\Users\\Indo\\Desktop\\auto
        state: directory

    - name: Copy system report to Windows
      win_copy:
        src: /tmp/system_details
        dest: C:\\Users\\Indo\\Desktop\\auto\\system_details.txt

    - name: Copy update_excel.py to Windows
      win_copy:
        src: /root/window/update_excel.py
        dest: C:\\Users\\Indo\\Desktop\\auto\\update_excel.py

    - name: Run update_excel.py on Windows
      win_command: python C:\\Users\\Indo\\Desktop\\auto\\update_excel.py
      register: run_output
      failed_when: run_output.rc != 0
      changed_when: false

    - name: Show update_excel.py output
      debug:
        var: run_output.stdout_lines




